### ISSUE TITLE
libraries

### ISSUE THREAD

**Issue by bosel** [OldNavi/OpenThermController#1]
He Ivan,

This looks interesting, but I cannot get it to build. Could you clarify what libraries are used?

Thanks!

**Comment by OldNavi** [comment]
Hi 
most libraries are just usual ESP and Arduino libraries except few additional
1/ https://github.com/ihormelnyk/opentherm_library
2 /https://github.com/nrwiersma/ESP8266Scheduler
3/ https://arduinojson.org
4/ https://pubsubclient.knolleary.net

All others are standard libs in ESP/Arduino packages coming with ESP8266 boards (which is used to run that code) - I was using WEMOS D1 R2 & mini board for that
