### ISSUE TITLE
Ophen therm controller integration from Home Assistent

### ISSUE THREAD

**Issue by roma1141r1** [OldNavi/OpenThermController#2]
Hello! Could you publish configuration.yaml for your OT controller, for beginners it is difficult to add json sensors, thank you!

**Comment by AlexanderLemesh** [comment]
Доброго времени.
Присоединяюсь к вышенаписанной просьбе.
Заранее спасибо

**Comment by OldNavi** [comment]
Пример здесь - http://arduino.ru/forum/programmirovanie/termostat-opentherm-na-esp8266?page=4#comment-503336

**Comment by AlexanderLemesh** [comment]
Спасибо. попробую разобратся
А каким mqtt-client пользуетесь в НА.
Я просто новичёк в этом понять умею а вот программировать не как.
Заранее спасибо.

**Comment by AlexanderLemesh** [comment]
Доброго времени.
Подскажите каким MQTT вы пользуетесь  в HA.
Заранее спасибо.

вс, 26 июл. 2020 г., 15:52 Ivan Sinitsin <notifications@github.com>:

**Comment by OldNavi** [comment]
Mosquitto.

**Comment by AlexanderLemesh** [comment]
Доброго времени. Подскажите пожалуйста литературу или что почитать по
поводу команд, я как бы в программировании полный ноль, хочу настроить НА
что бы хотя бы температуру показывал.

ср, 29 июл. 2020 г., 17:42 Ivan Sinitsin <notifications@github.com>:

**Comment by AlexanderLemesh** [comment]
Что где прописывать ??? Пожалуйста!!!!

пт, 14 авг. 2020 г., 12:02 Александр Лемеш <slemesh84@gmail.com>:
